name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
        env:
          ENV_TYPE: "production"
      - run: |
          if [ ! -f package-lock.json ]; then
            npm install
          fi
      - name: Configure Git with GitHub token
        run: |
          git config --global user.email "willclash@outlook.com"
          git config --global user.name "William Blanchet Lafrenière"
      - name: Install dependencies
        run: npm ci
      - name: Deploy application
        run: npm run deploy
