name: Test Pull Request
run-name: ${{ github.actor }} testing his pull request 🚀
on:
  pull_request:
    branches:
      - dev
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: 5.x
      - id: determine_version
        name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.14
        with:
          additionalArguments: /overrideconfig mode=Mainline
      - name: Install Dependencies
        run: npm i
        shell: bash
      - name: List Dependencies
        run: npm list --all > dependencies.txt
        shell: bash
      - name: Collect Dependencies
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Dependencies
          path: dependencies.txt
      - name: List Dependency Updates
        run: npm outdated > dependencyUpdates.txt
        shell: bash
      - name: Collect Dependency Updates
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Dependencies Updates
          path: dependencyUpdates.txt
      - name: Test
        run: npm test
        shell: bash
      - name: Build
        run: npm run build
        shell: bash
