name: Auto bump version and update PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-update-version:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Bump patch version in package.json
        id: bump
        run: |
          CURRENT_VERSION=$(jq -r .version package.json)
          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
          NEW_VERSION="$major.$minor.$((patch + 1))"
          jq --arg v "$NEW_VERSION" '.version = $v' package.json > tmp.json && mv tmp.json package.json
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit bumped version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add package.json
          git commit -m "chore: bump version to v${{ steps.bump.outputs.new_version }}"
          git push

      - name: Get PR number and commits
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            return {
              number: pr.number,
              base: pr.base.ref,
              head: pr.head.ref
            };

      - name: Get list of commit messages
        id: messages
        run: |
          MESSAGES=$(git log origin/${{ steps.pr.outputs.base }}..HEAD --pretty=format:"- %s")
          echo "messages<<EOF" >> $GITHUB_OUTPUT
          echo "$MESSAGES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update PR title and description
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ steps.pr.outputs.number }};
            const version = "${{ steps.bump.outputs.new_version }}";
            const body = `### Changes in v${version}\n\n${{ steps.messages.outputs.messages }}`;

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              title: `Update to v${version}`,
              body
            });
