name: Validate PR for Version and Description

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get PR info
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const title = pr.title;
            const body = pr.body || "";
            const number = pr.number;
            return { title, body, number };

      - name: Validate PR description
        run: |
          if [ -z "${{ steps.pr.outputs.body }}" ]; then
            echo "Error: PR description is required."
            exit 1
          fi

      - name: Get package.json version
        id: package
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Validate PR title contains version
        run: |
          TITLE="${{ steps.pr.outputs.title }}"
          VERSION="${{ steps.package.outputs.version }}"
          echo "PR Title: $TITLE"
          echo "package.json version: $VERSION"
          if [[ "$TITLE" != *"$VERSION"* ]]; then
            echo "Error: PR title must include version number ($VERSION) from package.json."
            exit 1
          fi

      - name: Check if package.json version was modified
        run: |
          git fetch origin main
          if git diff --name-only origin/main...HEAD | grep -q "package.json"; then
            if git diff origin/main...HEAD -- package.json | grep -q '"version"'; then
              echo "package.json version was modified."
            else
              echo "Error: package.json must have a version change."
              exit 1
            fi
          else
            echo "Error: package.json not modified."
            exit 1
          fi
